create table MEMBER(
	MEM_ID		VARCHAR2(30),
	MEM_PASS	VARCHAR2(100),
	MEM_NAME	VARCHAR2(30),
	MEM_EMAIL	VARCHAR2(50),
	MEM_PHONE	VARCHAR2(30),
	MEM_POINT	NUMBER,
	AUTH varchar2(50) not null,	
	PRIMARY	KEY(MEM_ID)
);

SELECT * FROM MEMBER;

DROP TABLE MEMBER CASCADE CONSTRAINTS;

UPDATE MEMBER SET AUTH='ROLE_ADMIN' WHERE MEM_ID='admin';