create table MEMBER(
	MEM_ID		VARCHAR2(30),
	MEM_PASS	VARCHAR2(30),
	MEM_NAME	VARCHAR2(30),
	MEM_EMAIL	VARCHAR2(30),
	MEM_PHONE	NUMBER,
	MEM_POINT	NUMBER,
	AUTH varchar2(50) not null,	
	PRIMARY	KEY(id)
);

SELECT * FROM MEMBER;

DROP TABEL MEMBER CASCADE CONSTRAINTS;

UPDATE MEMBER SET AUTH='ROLE_ADMIN' WHERE ID='ADMIN';

