create table OPTION_RESERVATION(
	OPTION_RESERVATION_ID   NUMBER primary key,
	REZ_ID 				    NUMBER references ROOM(ROOM_ID),
	OPTION_ID 			    NUMBER references OPTIONS(OPTION_ID),
	OPTION_RESERVATION_DATE DATE,
	ADULT 					NUMBER,
	CHILD 					NUMBER
)
select * from OPTION_RESERVATION order by OPTION_RESERVATION_DATE, OPTION_ID
delete from OPTION_RESERVATION
drop table OPTION_RESERVATION

select nvl(max(OPTION_RESERVATION_ID),0)+1 from OPTION_RESERVATION
