drop table question_board;
create table question_board(
  QUESTIONS_NUM        NUMBER         PRIMARY KEY, --
  MEM_ID               VARCHAR2(30)   REFERENCES MEMBER(MEM_ID) ON DELETE CASCADE,--
  
  QUESTIONS_CATEGORY   VARCHAR2(30)   NOT NULL, --
  QUESTIONS_PASS       NUMBER         NOT NULL,
  
  QUESTIONS_SUBJECT    VARCHAR2(100)  NOT NULL, --
  QUESTIONS_CONTENT    VARCHAR2(1000) NOT NULL,
  
  QUESTIONS_ANSWER     VARCHAR2(2000), 
  QUESTIONS_ORIGINAL   VARCHAR2(300),
  
  QUESTIONS_FILE       VARCHAR2(300),
  QUESTIONS_READCOUNT  NUMBER,--
  QUESTIONS_DATE       DATE DEFAULT SYSDATE NOT NULL --
);

select * from question_board;
create sequence QUESTION_SEQ start with 1 increment by 1;



INSERT INTO QUESTION_BOARD VALUES(
QUESTION_SEQ.NEXTVAL, 
'user01', 
'Test Category', 
1234, 
'Test Subject', 
'Test Content', 
'Test Answer', 
'Test Original', 
'Test File', 
0, 
sysdate);

select ROWNUM RN2 from QUESTION_BOARD;

SELECT ROWNUM RN2, T2.* FROM
(SELECT ROWNUM RN, T1.* FROM (SELECT * FROM QUESTION_BOARD WHERE MEM_ID = 'user01') T1 ) T2 
WHERE RN BETWEEN 5 AND 10;

SELECT T2.* FROM
(SELECT ROWNUM RN, T1.* 
FROM (SELECT * FROM QUESTION_BOARD WHERE MEM_ID = 'user01') T1 WHERE ROWNUM <= 10 ) T2 WHERE ROWNUM >= 5;

SELECT ROWNUM RN2, T2.* FROM
(SELECT ROWNUM RN1, T1.* FROM (SELECT * FROM QUESTION_BOARD WHERE MEM_ID = 'user01') T1 WHERE ROWNUM <= 10) T2
WHERE T2.RN1 >=5;
-- 1 페이지 10개 -> nowpage = 1 -> 1 * 10