create table REVIEW_BOARD (
	REVIEW_NUM 		 NUMBER primary key,
	MEM_ID 			 VARCHAR2(30) references MEMBER(MEM_ID),
	REVIEW_PASS 	 VARCHAR2(300),
	REVIEW_SUBJECT   VARCHAR2(300),
	REVIEW_CONTENT   VARCHAR2(1000),
	REVIEW_ORIGINAL  VARCHAR2(300),
	REVIEW_FILE 	 VARCHAR2(300),
	REVIEW_DATE 	 DATE default sysdate,
	REVIEW_READCOUNT NUMBER,
	REVIEW_RECOMM 	 NUMBER
)